/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.objects;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SquarePeg extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7677870698309943965L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SquarePeg\",\"namespace\":\"com.example.objects\",\"fields\":[{\"name\":\"side\",\"type\":\"int\",\"doc\":\"Length of each side of the square peg face\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SquarePeg> ENCODER =
      new BinaryMessageEncoder<SquarePeg>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SquarePeg> DECODER =
      new BinaryMessageDecoder<SquarePeg>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SquarePeg> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SquarePeg> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SquarePeg> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SquarePeg>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SquarePeg to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SquarePeg from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SquarePeg instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SquarePeg fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Length of each side of the square peg face */
  private int side;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SquarePeg() {}

  /**
   * All-args constructor.
   * @param side Length of each side of the square peg face
   */
  public SquarePeg(java.lang.Integer side) {
    this.side = side;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return side;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: side = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'side' field.
   * @return Length of each side of the square peg face
   */
  public int getSide() {
    return side;
  }


  /**
   * Sets the value of the 'side' field.
   * Length of each side of the square peg face
   * @param value the value to set.
   */
  public void setSide(int value) {
    this.side = value;
  }

  /**
   * Creates a new SquarePeg RecordBuilder.
   * @return A new SquarePeg RecordBuilder
   */
  public static com.example.objects.SquarePeg.Builder newBuilder() {
    return new com.example.objects.SquarePeg.Builder();
  }

  /**
   * Creates a new SquarePeg RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SquarePeg RecordBuilder
   */
  public static com.example.objects.SquarePeg.Builder newBuilder(com.example.objects.SquarePeg.Builder other) {
    if (other == null) {
      return new com.example.objects.SquarePeg.Builder();
    } else {
      return new com.example.objects.SquarePeg.Builder(other);
    }
  }

  /**
   * Creates a new SquarePeg RecordBuilder by copying an existing SquarePeg instance.
   * @param other The existing instance to copy.
   * @return A new SquarePeg RecordBuilder
   */
  public static com.example.objects.SquarePeg.Builder newBuilder(com.example.objects.SquarePeg other) {
    if (other == null) {
      return new com.example.objects.SquarePeg.Builder();
    } else {
      return new com.example.objects.SquarePeg.Builder(other);
    }
  }

  /**
   * RecordBuilder for SquarePeg instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SquarePeg>
    implements org.apache.avro.data.RecordBuilder<SquarePeg> {

    /** Length of each side of the square peg face */
    private int side;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.objects.SquarePeg.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.side)) {
        this.side = data().deepCopy(fields()[0].schema(), other.side);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SquarePeg instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.objects.SquarePeg other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.side)) {
        this.side = data().deepCopy(fields()[0].schema(), other.side);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'side' field.
      * Length of each side of the square peg face
      * @return The value.
      */
    public int getSide() {
      return side;
    }


    /**
      * Sets the value of the 'side' field.
      * Length of each side of the square peg face
      * @param value The value of 'side'.
      * @return This builder.
      */
    public com.example.objects.SquarePeg.Builder setSide(int value) {
      validate(fields()[0], value);
      this.side = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'side' field has been set.
      * Length of each side of the square peg face
      * @return True if the 'side' field has been set, false otherwise.
      */
    public boolean hasSide() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'side' field.
      * Length of each side of the square peg face
      * @return This builder.
      */
    public com.example.objects.SquarePeg.Builder clearSide() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SquarePeg build() {
      try {
        SquarePeg record = new SquarePeg();
        record.side = fieldSetFlags()[0] ? this.side : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SquarePeg>
    WRITER$ = (org.apache.avro.io.DatumWriter<SquarePeg>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SquarePeg>
    READER$ = (org.apache.avro.io.DatumReader<SquarePeg>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.side);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.side = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.side = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










